In [1]:
import pandas as pd
import numpy as np
import matplotlib
import seaborn as sns
from scipy import stats
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB

In [2]:
mushroom_raw_df = pd.read_csv("/Users/eupirate/Desktop/CA_data_exp_visdual/mush.csv")

In [3]:
mushroom_raw_df.head()

,Mushroom ID,Cap Shape,Cap Color,Gill Size,Stalk Shape,Habitat,Edibility,Market Demand,Spore Print Color,Population,...,Stalk Surface Below Ring,Stalk Color Above Ring,Stalk Color Below Ring,Veil Type,Veil Color,Growth Rate,Inspection Date,Incubation date,Temperature,Measurement
0,1,sunken,brown,narrow,tapering,leaves,edible,1,orange,abundant,...,silky,white,brown,universal,orange,0.973096463,03/07/2021,03/02/2021,49,C
1,?,convex,brown,narrow,tapering,urban,edible,2,brown,several,...,scaly,pink,white,universal,white,?,03/05/2023,03/04/2023,13,F
2,3,flat,brown,broad,enlarging,grasses,edible,8,yellow,scattered,...,?,gray,orange,partial,orange,1.977619113,01/08/2022,01/04/2022,10,C
3,4,sunken,gray,narrow,tapering,?,poisonous,4,orange,scattered,...,scaly,gray,orange,universal,yellow,2.272762762,02/10/2023,02/02/2023,22,C
4,5,flat,red,?,enlarging,urban,edible,7,brown,several,...,fibrous,orange,white,partial,white,0.718873785,01/09/2023,01/04/2023,9,C

In [4]:
mushroom_raw_df.describe()

       Temperature
count  1000.000000
mean     14.666000
std       8.698742
min       0.000000
25%       7.000000
50%      15.000000
75%      22.000000
max      49.000000

In [5]:
# mushroom_raw_categorical ["Cap Shape","Cap Color","Gill Size","Stalk Shape",
#                            "Habitat","Edibility","Spore Print Color","Population",
#                            "Odor","Bruising","Ring Type","Stalk Surface Above Ring","Stalk Surface Below Ring",
#                            "Stalk Color Above Ring","Stalk Color Below Ring","Veil Type","Veil Color",
#                            "Measurement"]

# mushroom_raw_num["Mushroom ID","Market Demand","Bruising","Growth Rate","Temperature"]
# mushroom_raw_date["Inspection Date","Incubation date",]

In [6]:
# mushroom categorical columns
mushroom_raw_df.replace("?",np.nan,inplace=True)

# Include Edibility
'''
df_bool = mushroom_raw_df[["Cap Shape","Cap Color","Gill Size","Stalk Shape",
                            "Habitat","Edibility","Spore Print Color","Population",
                            "Odor","Bruising","Ring Type","Stalk Surface Above Ring","Stalk Surface Below Ring",
                            "Stalk Color Above Ring","Stalk Color Below Ring","Veil Type","Veil Color",
                            "Measurement"]].isna()
#print(df_bool)
df_bool.isnull().sum()
'''


# Exclude Edibility Column
df_bool = mushroom_raw_df[["Cap Shape","Cap Color","Gill Size","Stalk Shape",
                            "Habitat","Spore Print Color","Population",
                            "Odor","Bruising","Ring Type","Stalk Surface Above Ring","Stalk Surface Below Ring",
                            "Stalk Color Above Ring","Stalk Color Below Ring","Veil Type","Veil Color",
                            "Measurement"]].isna()
#print(df_bool)
df_bool.isnull().sum()

Cap Shape                   0
Cap Color                   0
Gill Size                   0
Stalk Shape                 0
Habitat                     0
Spore Print Color           0
Population                  0
Odor                        0
Bruising                    0
Ring Type                   0
Stalk Surface Above Ring    0
Stalk Surface Below Ring    0
Stalk Color Above Ring      0
Stalk Color Below Ring      0
Veil Type                   0
Veil Color                  0
Measurement                 0
dtype: int64

In [7]:
mushroom_raw_df.head()

,Mushroom ID,Cap Shape,Cap Color,Gill Size,Stalk Shape,Habitat,Edibility,Market Demand,Spore Print Color,Population,...,Stalk Surface Below Ring,Stalk Color Above Ring,Stalk Color Below Ring,Veil Type,Veil Color,Growth Rate,Inspection Date,Incubation date,Temperature,Measurement
0,1,sunken,brown,narrow,tapering,leaves,edible,1,orange,abundant,...,silky,white,brown,universal,orange,0.973096463,03/07/2021,03/02/2021,49,C
1,NaN,convex,brown,narrow,tapering,urban,edible,2,brown,several,...,scaly,pink,white,universal,white,NaN,03/05/2023,03/04/2023,13,F
2,3,flat,brown,broad,enlarging,grasses,edible,8,yellow,scattered,...,NaN,gray,orange,partial,orange,1.977619113,01/08/2022,01/04/2022,10,C
3,4,sunken,gray,narrow,tapering,NaN,poisonous,4,orange,scattered,...,scaly,gray,orange,universal,yellow,2.272762762,02/10/2023,02/02/2023,22,C
4,5,flat,red,NaN,enlarging,urban,edible,7,brown,several,...,fibrous,orange,white,partial,white,0.718873785,01/09/2023,01/04/2023,9,C

In [8]:
# include NaN, run describe()
mushroom_raw_df.describe()

       Temperature
count  1000.000000
mean     14.666000
std       8.698742
min       0.000000
25%       7.000000
50%      15.000000
75%      22.000000
max      49.000000

In [9]:
# now we drop all rows with any NaN values
mushroom_drop_NaN = mushroom_raw_df.dropna()
mushroom_drop_NaN.describe()

       Temperature
count   119.000000
mean     14.848739
std       8.999660
min       0.000000
25%       8.000000
50%      14.000000
75%      23.000000
max      49.000000

# Before dropping NaN, we had 1000 rows of data, after dropped NaN, we only have 119 rows of data to work with, which is not a good representation of the dataset. I think we should explore other approaches to replace with NaN values.

# Identified those columns are mushroom's feature categorical columns, we choose to apply mode to replace NaN with the most common value of a column

# With a better understanding of the data, Edibility column is excluded from the mode replacement, as we don't want to misclassify or make inaccurate predictions, we want to ensure predict mushroom edibility safely.

In [10]:
# Exclude Edibility Column, it will be handled seprately soon.
for column in mushroom_raw_df.select_dtypes(include='object').columns:
    mushroom_raw_df[column].fillna(mushroom_raw_df[column].mode()[0], inplace=True)
#print(mushroom_raw_df)
#mushroom_raw_df.head()
mushroom_raw_df.describe()

       Temperature
count  1000.000000
mean     14.666000
std       8.698742
min       0.000000
25%       7.000000
50%      15.000000
75%      22.000000
max      49.000000

# By applying mode to replace NaN, we have successfully preserved 1000 rows in count, mean remained at 14.666, std at 8.698742 as original raw data set.

In [11]:
# We need to address column Mushroom ID's indexing sequence - starting from 1
mushroom_raw_df.index = range(1,len(mushroom_raw_df)+1)
mushroom_raw_df["Mushroom ID"] = mushroom_raw_df.index
print(mushroom_raw_df.index)

#mushroom_raw_df.head()

mushroom_raw_df.describe()

RangeIndex(start=1, stop=1001, step=1)

       Mushroom ID  Temperature
count  1000.000000  1000.000000
mean    500.500000    14.666000
std     288.819436     8.698742
min       1.000000     0.000000
25%     250.750000     7.000000
50%     500.500000    15.000000
75%     750.250000    22.000000
max    1000.000000    49.000000

In [12]:
# We want to ensure# re either Yes or No, we can convert it to 1 as Yes, 0 as No, but first let's replace ? with mode  columns of Market Demand and Bruisin values don't have missing or incorrect values
print(mushroom_raw_df[["Market Demand", "Bruising"]].head(20))

   Market Demand Bruising
1              1      Yes
2              2      Yes
3              8      Yes
4              4      Yes
5              7      Yes
6              6       No
7              5      Yes
8              3       No
9              7      Yes
10             3      Yes
11             3      Yes
12             2      Yes
13             8      Yes
14             9      Yes
15             5      Yes
16             3       No
17            10      Yes
18             1      Yes
19             3       No
20            10      Yes

In [13]:
print(mushroom_raw_df.isnull().sum())
mushroom_raw_df.head(21)
#mushroom_raw_df.describe()

Mushroom ID                 0
Cap Shape                   0
Cap Color                   0
Gill Size                   0
Stalk Shape                 0
Habitat                     0
Edibility                   0
Market Demand               0
Spore Print Color           0
Population                  0
Odor                        0
Bruising                    0
Ring Type                   0
Stalk Surface Above Ring    0
Stalk Surface Below Ring    0
Stalk Color Above Ring      0
Stalk Color Below Ring      0
Veil Type                   0
Veil Color                  0
Growth Rate                 0
Inspection Date             0
Incubation date             0
Temperature                 0
Measurement                 0
dtype: int64

,Mushroom ID,Cap Shape,Cap Color,Gill Size,Stalk Shape,Habitat,Edibility,Market Demand,Spore Print Color,Population,...,Stalk Surface Below Ring,Stalk Color Above Ring,Stalk Color Below Ring,Veil Type,Veil Color,Growth Rate,Inspection Date,Incubation date,Temperature,Measurement
1,1,sunken,brown,narrow,tapering,leaves,edible,1,orange,abundant,...,silky,white,brown,universal,orange,0.973096463,03/07/2021,03/02/2021,49,C
2,2,convex,brown,narrow,tapering,urban,edible,2,brown,several,...,scaly,pink,white,universal,white,0.502267005,03/05/2023,03/04/2023,13,F
3,3,flat,brown,broad,enlarging,grasses,edible,8,yellow,scattered,...,silky,gray,orange,partial,orange,1.977619113,01/08/2022,01/04/2022,10,C
4,4,sunken,gray,narrow,tapering,urban,poisonous,4,orange,scattered,...,scaly,gray,orange,universal,yellow,2.272762762,02/10/2023,02/02/2023,22,C
5,5,flat,red,narrow,enlarging,urban,edible,7,brown,several,...,fibrous,orange,white,partial,white,0.718873785,01/09/2023,01/04/2023,9,C
6,6,bell,gray,narrow,tapering,grasses,poisonous,6,yellow,several,...,silky,orange,white,universal,orange,14.02415593,04/11/2023,04/05/2023,21,C
7,7,flat,brown,broad,tapering,woods,edible,5,yellow,scattered,...,scaly,white,white,universal,white,4.320348762,02/08/2023,02/04/2023,13,C
8,8,sunken,red,narrow,enlarging,urban,edible,3,yellow,several,...,silky,gray,orange,partial,yellow,1.450596518,02/07/2023,02/05/2023,2,C
9,9,conical,yellow,narrow,enlarging,grasses,edible,7,yellow,solitary,...,fibrous,brown,gray,universal,orange,3.545415336,01/07/2023,01/01/2023,8,C
10,10,bell,gray,broad,tapering,paths,poisonous,3,white,numerous,...,scaly,white,white,universal,yellow,3.866757255,04/05/2023,04/01/2023,10,C
11,11,sunken,white,broad,enlarging,urban,edible,3,black,numerous,...,fibrous,gray,pink,universal,brown,9.468676774,03/12/2023,03/05/2023,26,C
12,12,conical,brown,broad,enlarging,leaves,edible,2,brown,scattered,...,scaly,gray,gray,partial,yellow,3.544817568,05/06/2023,05/01/2023,6,C
13,13,bell,yellow,broad,enlarging,leaves,edible,8,brown,numerous,...,silky,gray,pink,universal,yellow,4.471316648,01/02/2022,01/02/2022,18,C
14,14,bell,brown,narrow,enlarging,urban,poisonous,9,brown,numerous,...,silky,white,gray,partial,white,1.154902118,03/09/2023,03/02/2023,20,C
15,15,conical,gray,narrow,enlarging,woods,edible,5,brown,numerous,...,fibrous,white,gray,universal,white,2.144728044,05/02/2023,05/02/2023,16,C
16,16,convex,brown,narrow,enlarging,urban,edible,3,yellow,solitary,...,fibrous,brown,brown,partial,white,3.392187959,02/11/2023,02/02/2023,13,C
17,17,flat,gray,broad,tapering,urban,edible,10,orange,solitary,...,fibrous,white,brown,partial,yellow,4.745231837,04/07/2022,04/03/2022,23,C
18,18,conical,brown,narrow,enlarging,urban,poisonous,1,brown,numerous,...,smooth,brown,gray,universal,brown,4.373511264,05/11/2020,05/05/2020,20,C
19,19,convex,red,broad,tapering,urban,poisonous,3,black,solitary,...,smooth,pink,gray,universal,yellow,0.502267005,02/05/2023,02/05/2023,12,C
20,20,conical,brown,narrow,tapering,urban,edible,10,brown,scattered,...,fibrous,orange,gray,partial,brown,2.806382872,03/08/2023,03/01/2023,23,C
21,21,sunken,gray,narrow,tapering,urban,edible,3,black,scattered,...,silky,brown,brown,partial,white,0.972110245,04/10/2023,04/04/2023,21,C

In [14]:
# We can replace Bruising's Yes to 1 and No to 0 
mushroom_raw_df["Bruising"] = mushroom_raw_df["Bruising"].replace({"Yes": 1, "No": 0})
print(mushroom_raw_df[["Bruising"]].head(30))

    Bruising
1          1
2          1
3          1
4          1
5          1
6          0
7          1
8          0
9          1
10         1
11         1
12         1
13         1
14         1
15         1
16         0
17         1
18         1
19         0
20         1
21         0
22         1
23         1
24         1
25         1
26         0
27         1
28         1
29         0
30         0

In [15]:
print(mushroom_raw_df["Growth Rate"])
mushroom_raw_df["Growth Rate"].isnull().sum()
mushroom_raw_df.head()
mushroom_raw_df.describe()

1       0.973096463
2       0.502267005
3       1.977619113
4       2.272762762
5       0.718873785
           ...
996     3.755729472
997     0.502267005
998     11.25839107
999     4.964073966
1000    4.451239984
Name: Growth Rate, Length: 1000, dtype: object

       Mushroom ID     Bruising  Temperature
count  1000.000000  1000.000000  1000.000000
mean    500.500000     0.559000    14.666000
std     288.819436     0.496755     8.698742
min       1.000000     0.000000     0.000000
25%     250.750000     0.000000     7.000000
50%     500.500000     1.000000    15.000000
75%     750.250000     1.000000    22.000000
max    1000.000000     1.000000    49.000000