In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
from sklearn.impute import KNNImputer, SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

In [2]:
df=pd.read_csv("/Users/janet.xuishi/Documents/CA2 - Data Exploration amp Preparation - Instructions-20240319/ML_Data_Return.csv")

In [3]:
df.head()

,ID,Entry ID,Strategic Sale,Destination,Group,Date,Sequence,Product,Qty,Total Value,...,Logistic Partner,Deposit,Replacement,Market Demand,Quarter,Week,Strateg Prod,Strat Customer,ABC,Customer Group
0,57,17592,1,?,7,1/23/2021,8,4482,250,$112.50,...,C2,L2,NO,2,2022Q3,4,0,YES,C,176
1,57,17899,1,?,7,5/1/2021,1,4486,2200,$550.00,...,C2,L2,NO,2,2022Q3,9,0,YES,C,176
2,66,18072,0,NL,2,6/26/2021,77,4440,30,$214.20,...,C6,L9,NO,3,2022Q4,1,0,No,B,3986
3,17,18181,1,US,2,8/2/2021,11,4440,62,$442.68,...,C2,L2,NO,1,2022Q3,9,0,No,B,684
4,55,18335,1,DE,7,9/13/2021,2,4481,250,$622.50,...,C6,L9,NO,3,2022Q4,12,0,No,C,521